import React from "react";
import { Dialog, DialogContent, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import {
  Download,
  Printer,
  Star,
  Eye,
  MousePointerClick,
  ShoppingCart,
  TrendingUp,
  TrendingDown,
  MessageCircle,
  Sparkles,
  PlayCircle,
  Globe2,
} from "lucide-react";
import { useLang } from "@/lib/i18n";

export type PerformanceData = {
  weekLabel: string;
  weekLabelZh: string;
  net: number;
  gross: number;
  storeViews: number;
  uniqueVisitors: number;
  avgSession: string;
  reviews: number;
  rating: number;
  orders: number;
  conversion: number;
  social: { wechat: number; xhs: number; douyin: number };
  topContent: { title: string; titleZh: string; platform: "wechat" | "xhs" | "douyin"; views: number; orders: number; revenue: number }[];
  breakdown: { direct: number; referred: number; bonus: number };
  vsLast: number;
};

const PLATFORM_META = {
  wechat: { label: "WeChat", labelZh: "微信", color: "text-emerald-700", bg: "bg-emerald-50", ring: "ring-emerald-200" },
  xhs: { label: "Xiaohongshu", labelZh: "小红书", color: "text-rose-700", bg: "bg-rose-50", ring: "ring-rose-200" },
  douyin: { label: "Douyin", labelZh: "抖音", color: "text-zinc-900", bg: "bg-zinc-100", ring: "ring-zinc-300" },
};

function fmt(n: number) {
  if (n >= 1000) return `${(n / 1000).toFixed(n >= 10000 ? 0 : 1)}k`;
  return n.toString();
}

export function PerformanceReportDialog({ open, onOpenChange, data }: { open: boolean; onOpenChange: (o: boolean) => void; data: PerformanceData }) {
  const { lang, t } = useLang();
  const totalSocial = data.social.wechat + data.social.xhs + data.social.douyin;
  const reportId = `PV-PR-${data.weekLabel.replace(/[, ]/g, "")}`;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-4xl p-0 overflow-hidden bg-white" onOpenAutoFocus={(e) => e.preventDefault()}>
        <DialogTitle className="sr-only">{t("Performance Report", "绩效报告")}</DialogTitle>

        <div className="bg-secondary/40 border-b border-border/60 px-6 py-3 flex items-center justify-between">
          <div className="flex items-center gap-2 text-xs text-muted-foreground">
            <Sparkles className="w-3.5 h-3.5 text-primary" />
            <span>{t("Generated by PayView Analytics", "由 PayView 数据分析生成")}</span>
          </div>
          <div className="flex gap-2">
            <Button size="sm" variant="ghost" className="h-8 gap-1.5 text-xs"><Printer className="w-3.5 h-3.5" />{t("Print", "打印")}</Button>
            <Button size="sm" className="h-8 gap-1.5 text-xs"><Download className="w-3.5 h-3.5" />{t("Download PDF", "下载 PDF")}</Button>
          </div>
        </div>

        <div className="max-h-[80vh] overflow-y-auto">
          <div className="bg-gradient-to-br from-[#0B271F] via-[#053828] to-[#0B271F] text-white p-8 relative overflow-hidden">
            <div className="absolute top-0 right-0 w-[400px] h-[400px] bg-emerald-500/15 rounded-full blur-[100px] -translate-y-1/3 translate-x-1/4" />
            <div className="relative z-10 flex justify-between items-start gap-6">
              <div>
                <div className="inline-flex items-center gap-2 bg-white/10 border border-white/20 px-3 py-1 rounded-full text-[11px] uppercase tracking-wider font-semibold mb-4">
                  <PayViewLogo className="w-3 h-3" />
                  {t("PayView Performance Report", "PayView 绩效报告")}
                </div>
                <h1 className="text-2xl md:text-3xl font-display font-bold tracking-tight">
                  {t(`Week of ${data.weekLabel}`, `${data.weekLabelZh} 当周`)}
                </h1>
                <p className="text-emerald-100/80 text-sm mt-1">
                  {t(`Matt Barros · Elite Influencer · Report ${reportId}`, `马特·巴罗斯 · 精英影响者 · 报告编号 ${reportId}`)}
                </p>
              </div>
              <div className="text-right shrink-0">
                <div className="text-[11px] uppercase tracking-wider text-emerald-100/70 font-semibold">{t("Total Paid", "本期到账")}</div>
                <div className="text-3xl md:text-4xl font-display font-bold tabular-nums">¥{data.net.toFixed(2)}</div>
                <div className={`inline-flex items-center gap-1 text-xs font-semibold mt-1 ${data.vsLast >= 0 ? "text-emerald-300" : "text-rose-300"}`}>
                  {data.vsLast >= 0 ? <TrendingUp className="w-3.5 h-3.5" /> : <TrendingDown className="w-3.5 h-3.5" />}
                  {data.vsLast >= 0 ? "+" : ""}{(data.vsLast * 100).toFixed(1)}% {t("vs prior week", "环比上周")}
                </div>
              </div>
            </div>
          </div>

          <div className="p-8 space-y-8 bg-white text-zinc-900">

            <Section title={t("Why you got paid this week", "本周收入构成")} subtitle={t("Aggregated from your storefront, social channels, and conversions.", "综合来自店铺、社交渠道与转化数据。")}>
              <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
                <Stat icon={<Eye className="w-4 h-4" />} label={t("Storefront Views", "店铺浏览")} value={fmt(data.storeViews)} sub={t(`${fmt(data.uniqueVisitors)} unique`, `${fmt(data.uniqueVisitors)} 独立访客`)} />
                <Stat icon={<MousePointerClick className="w-4 h-4" />} label={t("Conversion", "转化率")} value={`${(data.conversion * 100).toFixed(1)}%`} sub={t(`${data.orders} orders`, `${data.orders} 笔订单`)} />
                <Stat icon={<Star className="w-4 h-4" />} label={t("Reviews", "用户评价")} value={data.rating.toFixed(1)} sub={t(`${data.reviews} new`, `${data.reviews} 条新增`)} accent="amber" />
                <Stat icon={<Globe2 className="w-4 h-4" />} label={t("Social Reach", "社交触达")} value={fmt(totalSocial)} sub={t("3 platforms", "3 个平台")} />
              </div>
            </Section>

            <Section title={t("Conversion funnel", "转化漏斗")} subtitle={t("How impressions became orders.", "曝光如何转化为订单。")}>
              <div className="rounded-2xl border border-border/60 bg-secondary/30 p-5">
                {[
                  { label: t("Social impressions", "社交曝光"), value: totalSocial, pct: 100 },
                  { label: t("Storefront visits", "店铺访问"), value: data.storeViews, pct: (data.storeViews / totalSocial) * 100 },
                  { label: t("Add to cart", "加入购物车"), value: Math.round(data.orders / data.conversion * 0.18), pct: (Math.round(data.orders / data.conversion * 0.18) / totalSocial) * 100 },
                  { label: t("Orders placed", "完成下单"), value: data.orders, pct: (data.orders / totalSocial) * 100 },
                ].map((s, i, arr) => {
                  const w = Math.max(8, (s.value / arr[0].value) * 100);
                  return (
                    <div key={s.label} className="mb-3 last:mb-0">
                      <div className="flex justify-between text-xs mb-1">
                        <span className="text-zinc-600">{s.label}</span>
                        <span className="tabular-nums font-semibold">{s.value.toLocaleString()} <span className="text-zinc-400 font-normal">({s.pct.toFixed(2)}%)</span></span>
                      </div>
                      <div className="h-7 bg-white border border-border/50 rounded-md overflow-hidden">
                        <div
                          className="h-full bg-gradient-to-r from-primary to-emerald-500 rounded-md flex items-center px-2 text-[10px] text-white font-semibold"
                          style={{ width: `${w}%` }}
                        >
                          {i === arr.length - 1 ? `¥${(data.net / s.value).toFixed(2)} ${t("/ order", "/ 单")}` : ""}
                        </div>
                      </div>
                    </div>
                  );
                })}
              </div>
            </Section>

            <Section title={t("Channel performance", "渠道表现")} subtitle={t("Where your audience came from.", "粉丝从哪里来。")}>
              <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
                {(["wechat", "xhs", "douyin"] as const).map((p) => {
                  const meta = PLATFORM_META[p];
                  const v = data.social[p];
                  const pct = (v / totalSocial) * 100;
                  return (
                    <div key={p} className={`rounded-xl border border-border/50 p-4 ${meta.bg} ring-1 ${meta.ring}`}>
                      <div className="flex items-center justify-between mb-3">
                        <div className={`text-sm font-semibold ${meta.color}`}>{lang === "zh" ? meta.labelZh : meta.label}</div>
                        <span className={`text-[10px] font-bold ${meta.color}`}>{pct.toFixed(0)}%</span>
                      </div>
                      <div className={`text-2xl font-display font-bold tabular-nums ${meta.color}`}>{fmt(v)}</div>
                      <div className="text-[11px] text-zinc-500 mt-0.5">{t("impressions", "曝光数")}</div>
                      <div className="h-1.5 bg-white/60 rounded-full mt-3 overflow-hidden">
                        <div className={`h-full ${p === "wechat" ? "bg-emerald-500" : p === "xhs" ? "bg-rose-500" : "bg-zinc-700"}`} style={{ width: `${pct}%` }} />
                      </div>
                    </div>
                  );
                })}
              </div>
            </Section>

            <Section title={t("Top performing content", "高转化内容")} subtitle={t("Posts that drove the most paid revenue this week.", "本周带来最多收入的内容。")}>
              <div className="rounded-2xl border border-border/60 overflow-hidden">
                <table className="w-full text-sm">
                  <thead className="bg-secondary/40 text-[11px] uppercase tracking-wider text-zinc-500 font-semibold">
                    <tr>
                      <th className="text-left px-4 py-2.5">{t("Content", "内容")}</th>
                      <th className="text-left px-4 py-2.5">{t("Channel", "渠道")}</th>
                      <th className="text-right px-4 py-2.5">{t("Views", "浏览")}</th>
                      <th className="text-right px-4 py-2.5">{t("Orders", "订单")}</th>
                      <th className="text-right px-4 py-2.5">{t("Revenue", "收入")}</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-border/50 bg-white">
                    {data.topContent.map((c, i) => {
                      const pmeta = PLATFORM_META[c.platform];
                      const Icon = c.platform === "wechat" ? MessageCircle : c.platform === "xhs" ? ShoppingCart : PlayCircle;
                      return (
                        <tr key={i}>
                          <td className="px-4 py-3 text-zinc-900 font-medium">{lang === "zh" ? c.titleZh : c.title}</td>
                          <td className="px-4 py-3">
                            <span className={`inline-flex items-center gap-1.5 text-xs font-semibold ${pmeta.color}`}>
                              <Icon className="w-3.5 h-3.5" />
                              {lang === "zh" ? pmeta.labelZh : pmeta.label}
                            </span>
                          </td>
                          <td className="px-4 py-3 text-right tabular-nums text-zinc-700">{fmt(c.views)}</td>
                          <td className="px-4 py-3 text-right tabular-nums text-zinc-700">{c.orders}</td>
                          <td className="px-4 py-3 text-right tabular-nums font-semibold text-primary">¥{c.revenue.toFixed(2)}</td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>
            </Section>

            <Section title={t("Earnings breakdown", "收入明细")} subtitle={t("How the total paid was calculated.", "本期到账金额构成。")}>
              <div className="rounded-2xl border border-border/60 bg-secondary/20 p-5 space-y-3">
                <BreakdownRow label={t("Direct sales commission", "直接销售佣金")} value={data.breakdown.direct} pct={data.breakdown.direct / data.gross} />
                <BreakdownRow label={t("Referred orders commission", "推荐订单佣金")} value={data.breakdown.referred} pct={data.breakdown.referred / data.gross} />
                <BreakdownRow label={t("Performance bonus", "绩效奖励")} value={data.breakdown.bonus} pct={data.breakdown.bonus / data.gross} />
                <div className="border-t border-border/60 pt-3 flex justify-between text-sm">
                  <span className="text-zinc-600">{t("Gross earnings", "毛收入")}</span>
                  <span className="font-semibold tabular-nums">¥{data.gross.toFixed(2)}</span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-zinc-600">{t("Withholding tax (6%)", "代扣代缴税款 (6%)")}</span>
                  <span className="font-semibold tabular-nums text-rose-600">- ¥{(data.gross - data.net).toFixed(2)}</span>
                </div>
                <div className="border-t border-border/60 pt-3 flex justify-between items-baseline">
                  <span className="font-display font-semibold text-zinc-900">{t("Net paid", "净到账")}</span>
                  <span className="text-2xl font-display font-bold tabular-nums text-primary">¥{data.net.toFixed(2)}</span>
                </div>
              </div>
            </Section>

            <div className="text-[10px] text-zinc-500 leading-relaxed border-t border-border/60 pt-4 flex items-start gap-3">
              <PayViewLogo className="w-4 h-4 mt-0.5 shrink-0" />
              <p>
                {t(
                  `This report was automatically generated by PayView Analytics on behalf of More Health. Metrics are sourced from verified storefront sessions, attributed social impressions, and validated order events. Withholding and disbursement handled by PayView Tax Services (Shenzhen) Co., Ltd. Funds settled via ICBC. Report ID ${reportId}.`,
                  `本报告由 PayView 数据分析为 More Health 自动生成。数据来自经核验的店铺会话、归因社交曝光与有效订单事件。代扣代缴及打款由派维税务服务（深圳）有限公司处理，资金通过中国工商银行结算。报告编号 ${reportId}。`
                )}
              </p>
            </div>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}

function PayViewLogo({ className = "" }: { className?: string }) {
  return (
    <svg viewBox="0 0 24 24" className={className} fill="currentColor">
      <path d="M3 4 L12 20 L21 4 L17 4 L12 13 L7 4 Z" />
    </svg>
  );
}

function Section({ title, subtitle, children }: { title: string; subtitle?: string; children: React.ReactNode }) {
  return (
    <section>
      <div className="mb-3">
        <h2 className="text-base font-display font-semibold text-zinc-900">{title}</h2>
        {subtitle && <p className="text-xs text-zinc-500 mt-0.5">{subtitle}</p>}
      </div>
      {children}
    </section>
  );
}

function Stat({ icon, label, value, sub, accent }: { icon: React.ReactNode; label: string; value: string; sub: string; accent?: "amber" }) {
  return (
    <div className="rounded-xl border border-border/60 bg-card p-4">
      <div className={`inline-flex items-center justify-center w-8 h-8 rounded-lg mb-2 ${accent === "amber" ? "bg-amber-100 text-amber-700" : "bg-primary/10 text-primary"}`}>{icon}</div>
      <div className="text-[10px] uppercase tracking-wider text-zinc-500 font-semibold">{label}</div>
      <div className="text-2xl font-display font-bold tabular-nums text-zinc-900 mt-0.5">{value}</div>
      <div className="text-[11px] text-zinc-500">{sub}</div>
    </div>
  );
}

function BreakdownRow({ label, value, pct }: { label: string; value: number; pct: number }) {
  return (
    <div>
      <div className="flex justify-between text-sm mb-1">
        <span className="text-zinc-700">{label}</span>
        <span className="font-semibold tabular-nums">¥{value.toFixed(2)}</span>
      </div>
      <div className="h-1.5 bg-white border border-border/50 rounded-full overflow-hidden">
        <div className="h-full bg-gradient-to-r from-primary/80 to-emerald-500" style={{ width: `${pct * 100}%` }} />
      </div>
    </div>
  );
}
